endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        data: 'This is customized QR code'
        # Label is not implemented for SvgWriter
        label_text: 'This is the label'
        label_font_path: '%kernel.project_dir%/public/qrCode/logoSite.png'
        label_font_size: 20
        label_alignment: 'center'
    custom:
        writer: Endroid\QrCode\Writer\SvgWriter
        writer_options:
            exclude_xml_declaration: true # default: false
        data: 'This is customized QR code'
        size: 150
        encoding: 'UTF-8'
        error_correction_level: 'high' # 'low', 'medium', 'quartile', or 'high'
        round_block_size_mode: 'margin'
        label_font_path: '%kernel.project_dir%/public/qrCode/logoSite.png'
        logo_resize_to_width: 150
        logo_punchout_background: true
        validate_result: false